name: test/image

base: gcr.io/distroless/static:nonroot

config:
  user: alice
  workingdir: "/workspace" # NB: workingDir is invalid :(
  labels:
    cool: a label

annotations:
  hey: this
  is: cool too

layers:
- archive:
    url: https://partner-images.canonical.com/oci/impish/20210913/ubuntu-impish-oci-amd64-root.tar.gz
    sha256: a8cb4eb74f7b22bad76b72793cce864706aaa82299e0ac0581de79eca510b7b4
    size: 29528000
  # Override file contents in the layer from archive.
  files:
  - name: usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
    contents: this should be fine

- files:
  - name: hello
    contents: world
    mode: 0644

- files:
  - name: seeya
    contents: fella
  - name: cool
    data: 8J+lsA==
