base: gcr.io/distroless/static:nonroot

config:
  user: alice
  workingdir: "/workspace" # NB: workingDir is invalid :(

annotations:
  hey: this
  is: cool

layers:
- files:
  - name: hello
    contents: hello
  - name: world
    contents: world
    mode: 0644

- files:
  - name: seeya
    contents: fella
  - name: goodbye
    contents: later
  - name: cool
    data: 8J+lsA==
